Chapter 2 정리(작성중)
ghooz1204/elegant-OOP-handling pull request #45
Opened 2021-11-20 14:56 UTC by SewookHan

close #41

2021-11-20 17:13 UTC, ghooz1204 requested changes
.gitignore에 .DS_Store 추가하고 .DS_Store 파일 추적 안되게 해주시면 감사하겠습니다.

2021-11-21 00:12 UTC, ghtjr026 approved these changes

2021-11-21 00:12 UTC, ghtjr026 commented
지적 사항 없음

2021-11-21 00:13 UTC, ghooz1204 approved these changes
감사합니다.

2021-11-21 00:13 UTC, merged